<?xml version = "1.0" ?>
<?xml-stylesheet type="text/xsl" href="SystemBOM.xsl"?>
<!DOCTYPE GRID [
  <!ELEMENT GRID (BANDS, COLUMNS, ROWS*)>
  <!ATTLIST GRID ExportVersion CDATA #REQUIRED>
  <!ELEMENT BANDS (BAND*)>
  <!ELEMENT BAND EMPTY>
  <!ATTLIST BAND Index CDATA #REQUIRED>
  <!ATTLIST BAND Caption CDATA #IMPLIED>
  <!ELEMENT COLUMNS (COLUMN*)>
  <!ELEMENT COLUMN EMPTY>
  <!ATTLIST COLUMN Name CDATA #REQUIRED>
  <!ATTLIST COLUMN Caption CDATA #IMPLIED>
  <!ATTLIST COLUMN Index CDATA #REQUIRED>
  <!ATTLIST COLUMN BandIndex CDATA #REQUIRED>
  <!ATTLIST COLUMN RowIndex CDATA #REQUIRED>
  <!ATTLIST COLUMN ColIndex CDATA #REQUIRED>
  <!ATTLIST COLUMN Width CDATA #IMPLIED>
  <!ELEMENT GROUP (GROUP*, ROW*)>
  <!ATTLIST GROUP GroupText CDATA #IMPLIED>
  <!ELEMENT ROWS (ROW*)>
  <!ELEMENT ROW EMPTY>
  <!ATTLIST ROW Address1 CDATA #IMPLIED>
  <!ATTLIST ROW Address2 CDATA #IMPLIED>
  <!ATTLIST ROW Address3 CDATA #IMPLIED>
  <!ATTLIST ROW Address4 CDATA #IMPLIED>
  <!ATTLIST ROW Alternate_Manufacturer CDATA #IMPLIED>
  <!ATTLIST ROW Alternate_PartNumber CDATA #IMPLIED>
  <!ATTLIST ROW Application_BuildNumber CDATA #IMPLIED>
  <!ATTLIST ROW ApprovedBy CDATA #IMPLIED>
  <!ATTLIST ROW Author CDATA #IMPLIED>
  <!ATTLIST ROW CheckedBy CDATA #IMPLIED>
  <!ATTLIST ROW Code_IPC CDATA #IMPLIED>
  <!ATTLIST ROW Code_JEDEC CDATA #IMPLIED>
  <!ATTLIST ROW Comment CDATA #IMPLIED>
  <!ATTLIST ROW CompanyName CDATA #IMPLIED>
  <!ATTLIST ROW Component_Kind CDATA #IMPLIED>
  <!ATTLIST ROW ComponentKind CDATA #IMPLIED>
  <!ATTLIST ROW ComponentLink1Description CDATA #IMPLIED>
  <!ATTLIST ROW ComponentLink1URL CDATA #IMPLIED>
  <!ATTLIST ROW ComponentLink2Description CDATA #IMPLIED>
  <!ATTLIST ROW ComponentLink2URL CDATA #IMPLIED>
  <!ATTLIST ROW CompType CDATA #IMPLIED>
  <!ATTLIST ROW CurrentDate CDATA #IMPLIED>
  <!ATTLIST ROW CurrentTime CDATA #IMPLIED>
  <!ATTLIST ROW DatasheetVersion CDATA #IMPLIED>
  <!ATTLIST ROW Date CDATA #IMPLIED>
  <!ATTLIST ROW Description CDATA #IMPLIED>
  <!ATTLIST ROW Designator CDATA #IMPLIED>
  <!ATTLIST ROW Designator_X_Mil_ CDATA #IMPLIED>
  <!ATTLIST ROW Designator_X_mm_ CDATA #IMPLIED>
  <!ATTLIST ROW Designator_Y_Mil_ CDATA #IMPLIED>
  <!ATTLIST ROW Designator_Y_mm_ CDATA #IMPLIED>
  <!ATTLIST ROW DesignItemId CDATA #IMPLIED>
  <!ATTLIST ROW Document CDATA #IMPLIED>
  <!ATTLIST ROW DocumentFullPathAndName CDATA #IMPLIED>
  <!ATTLIST ROW DocumentName CDATA #IMPLIED>
  <!ATTLIST ROW DocumentNumber CDATA #IMPLIED>
  <!ATTLIST ROW DrawnBy CDATA #IMPLIED>
  <!ATTLIST ROW Engineer CDATA #IMPLIED>
  <!ATTLIST ROW Footprint CDATA #IMPLIED>
  <!ATTLIST ROW Height_Mil_ CDATA #IMPLIED>
  <!ATTLIST ROW Height_mm_ CDATA #IMPLIED>
  <!ATTLIST ROW Ibis_Model CDATA #IMPLIED>
  <!ATTLIST ROW ImagePath CDATA #IMPLIED>
  <!ATTLIST ROW Index CDATA #IMPLIED>
  <!ATTLIST ROW ItemGUID CDATA #IMPLIED>
  <!ATTLIST ROW LatestRevisionDate CDATA #IMPLIED>
  <!ATTLIST ROW LatestRevisionNote CDATA #IMPLIED>
  <!ATTLIST ROW Library_Name CDATA #IMPLIED>
  <!ATTLIST ROW Library_Reference CDATA #IMPLIED>
  <!ATTLIST ROW LibRef CDATA #IMPLIED>
  <!ATTLIST ROW LogicalDesignator CDATA #IMPLIED>
  <!ATTLIST ROW Manufacturer CDATA #IMPLIED>
  <!ATTLIST ROW Model_Footprint CDATA #IMPLIED>
  <!ATTLIST ROW Model_PCB3D CDATA #IMPLIED>
  <!ATTLIST ROW Model_Signal_Integrity CDATA #IMPLIED>
  <!ATTLIST ROW Model_Simulation CDATA #IMPLIED>
  <!ATTLIST ROW Models CDATA #IMPLIED>
  <!ATTLIST ROW ModifiedDate CDATA #IMPLIED>
  <!ATTLIST ROW MountType CDATA #IMPLIED>
  <!ATTLIST ROW Organization CDATA #IMPLIED>
  <!ATTLIST ROW PackageDescription CDATA #IMPLIED>
  <!ATTLIST ROW PackageReference CDATA #IMPLIED>
  <!ATTLIST ROW PackageVersion CDATA #IMPLIED>
  <!ATTLIST ROW PageSetup CDATA #IMPLIED>
  <!ATTLIST ROW PartNumber CDATA #IMPLIED>
  <!ATTLIST ROW PartType CDATA #IMPLIED>
  <!ATTLIST ROW PCB3D CDATA #IMPLIED>
  <!ATTLIST ROW PhysicalPath CDATA #IMPLIED>
  <!ATTLIST ROW Pins CDATA #IMPLIED>
  <!ATTLIST ROW Project CDATA #IMPLIED>
  <!ATTLIST ROW ProjectName CDATA #IMPLIED>
  <!ATTLIST ROW Published CDATA #IMPLIED>
  <!ATTLIST ROW Publisher CDATA #IMPLIED>
  <!ATTLIST ROW Quantity CDATA #IMPLIED>
  <!ATTLIST ROW Revision CDATA #IMPLIED>
  <!ATTLIST ROW RevisionGUID CDATA #IMPLIED>
  <!ATTLIST ROW RoHS CDATA #IMPLIED>
  <!ATTLIST ROW Rule CDATA #IMPLIED>
  <!ATTLIST ROW SheetNumber CDATA #IMPLIED>
  <!ATTLIST ROW SheetTotal CDATA #IMPLIED>
  <!ATTLIST ROW Signal_Integrity CDATA #IMPLIED>
  <!ATTLIST ROW Simulation CDATA #IMPLIED>
  <!ATTLIST ROW SourceLibraryName CDATA #IMPLIED>
  <!ATTLIST ROW Sub_Parts CDATA #IMPLIED>
  <!ATTLIST ROW SymbolCreator CDATA #IMPLIED>
  <!ATTLIST ROW SymbolVersion CDATA #IMPLIED>
  <!ATTLIST ROW Time CDATA #IMPLIED>
  <!ATTLIST ROW Title CDATA #IMPLIED>
  <!ATTLIST ROW U_M CDATA #IMPLIED>
  <!ATTLIST ROW UniqueIdName CDATA #IMPLIED>
  <!ATTLIST ROW UniqueIdPath CDATA #IMPLIED>
  <!ATTLIST ROW Value CDATA #IMPLIED>
  <!ATTLIST ROW Variant CDATA #IMPLIED>
  <!ATTLIST ROW VaultGUID CDATA #IMPLIED>
  <!ATTLIST ROW _ CDATA #IMPLIED>
  <!ATTLIST ROW _ID_ CDATA #IMPLIED>
  <!ATTLIST ROW _PARENTID_ CDATA #IMPLIED>
]>
<GRID ExportVersion="1.0">
  <BANDS>
    <BAND Index="0" Caption=""></BAND>
  </BANDS>
  <COLUMNS>
    <COLUMN Name="Address1" Caption="Address1" Index="0" BandIndex="0" RowIndex="0" ColIndex="0" Width="100"></COLUMN>
    <COLUMN Name="Address2" Caption="Address2" Index="1" BandIndex="0" RowIndex="0" ColIndex="1" Width="100"></COLUMN>
    <COLUMN Name="Address3" Caption="Address3" Index="2" BandIndex="0" RowIndex="0" ColIndex="2" Width="100"></COLUMN>
    <COLUMN Name="Address4" Caption="Address4" Index="3" BandIndex="0" RowIndex="0" ColIndex="3" Width="100"></COLUMN>
    <COLUMN Name="Alternate_Manufacturer" Caption="Alternate Manufacturer" Index="4" BandIndex="0" RowIndex="0" ColIndex="4" Width="100"></COLUMN>
    <COLUMN Name="Alternate_PartNumber" Caption="Alternate PartNumber" Index="5" BandIndex="0" RowIndex="0" ColIndex="5" Width="100"></COLUMN>
    <COLUMN Name="Application_BuildNumber" Caption="Application_BuildNumber" Index="6" BandIndex="0" RowIndex="0" ColIndex="6" Width="100"></COLUMN>
    <COLUMN Name="ApprovedBy" Caption="ApprovedBy" Index="7" BandIndex="0" RowIndex="0" ColIndex="7" Width="100"></COLUMN>
    <COLUMN Name="Author" Caption="Author" Index="8" BandIndex="0" RowIndex="0" ColIndex="8" Width="100"></COLUMN>
    <COLUMN Name="CheckedBy" Caption="CheckedBy" Index="9" BandIndex="0" RowIndex="0" ColIndex="9" Width="100"></COLUMN>
    <COLUMN Name="Code_IPC" Caption="Code_IPC" Index="10" BandIndex="0" RowIndex="0" ColIndex="10" Width="100"></COLUMN>
    <COLUMN Name="Code_JEDEC" Caption="Code_JEDEC" Index="11" BandIndex="0" RowIndex="0" ColIndex="11" Width="100"></COLUMN>
    <COLUMN Name="Comment" Caption="Comment" Index="12" BandIndex="0" RowIndex="0" ColIndex="12" Width="100"></COLUMN>
    <COLUMN Name="CompanyName" Caption="CompanyName" Index="13" BandIndex="0" RowIndex="0" ColIndex="13" Width="100"></COLUMN>
    <COLUMN Name="Component_Kind" Caption="Component Kind" Index="14" BandIndex="0" RowIndex="0" ColIndex="14" Width="100"></COLUMN>
    <COLUMN Name="ComponentKind" Caption="ComponentKind" Index="15" BandIndex="0" RowIndex="0" ColIndex="15" Width="100"></COLUMN>
    <COLUMN Name="ComponentLink1Description" Caption="ComponentLink1Description" Index="16" BandIndex="0" RowIndex="0" ColIndex="16" Width="100"></COLUMN>
    <COLUMN Name="ComponentLink1URL" Caption="ComponentLink1URL" Index="17" BandIndex="0" RowIndex="0" ColIndex="17" Width="100"></COLUMN>
    <COLUMN Name="ComponentLink2Description" Caption="ComponentLink2Description" Index="18" BandIndex="0" RowIndex="0" ColIndex="18" Width="100"></COLUMN>
    <COLUMN Name="ComponentLink2URL" Caption="ComponentLink2URL" Index="19" BandIndex="0" RowIndex="0" ColIndex="19" Width="100"></COLUMN>
    <COLUMN Name="CompType" Caption="CompType" Index="20" BandIndex="0" RowIndex="0" ColIndex="20" Width="100"></COLUMN>
    <COLUMN Name="CurrentDate" Caption="CurrentDate" Index="21" BandIndex="0" RowIndex="0" ColIndex="21" Width="100"></COLUMN>
    <COLUMN Name="CurrentTime" Caption="CurrentTime" Index="22" BandIndex="0" RowIndex="0" ColIndex="22" Width="100"></COLUMN>
    <COLUMN Name="DatasheetVersion" Caption="DatasheetVersion" Index="23" BandIndex="0" RowIndex="0" ColIndex="23" Width="100"></COLUMN>
    <COLUMN Name="Date" Caption="Date" Index="24" BandIndex="0" RowIndex="0" ColIndex="24" Width="100"></COLUMN>
    <COLUMN Name="Description" Caption="Description" Index="25" BandIndex="0" RowIndex="0" ColIndex="25" Width="100"></COLUMN>
    <COLUMN Name="Designator" Caption="Designator" Index="26" BandIndex="0" RowIndex="0" ColIndex="26" Width="100"></COLUMN>
    <COLUMN Name="Designator_X_Mil_" Caption="Designator-X&#40;Mil&#41;" Index="27" BandIndex="0" RowIndex="0" ColIndex="27" Width="100"></COLUMN>
    <COLUMN Name="Designator_X_mm_" Caption="Designator-X&#40;mm&#41;" Index="28" BandIndex="0" RowIndex="0" ColIndex="28" Width="100"></COLUMN>
    <COLUMN Name="Designator_Y_Mil_" Caption="Designator-Y&#40;Mil&#41;" Index="29" BandIndex="0" RowIndex="0" ColIndex="29" Width="100"></COLUMN>
    <COLUMN Name="Designator_Y_mm_" Caption="Designator-Y&#40;mm&#41;" Index="30" BandIndex="0" RowIndex="0" ColIndex="30" Width="100"></COLUMN>
    <COLUMN Name="DesignItemId" Caption="DesignItemId" Index="31" BandIndex="0" RowIndex="0" ColIndex="31" Width="100"></COLUMN>
    <COLUMN Name="Document" Caption="Document" Index="32" BandIndex="0" RowIndex="0" ColIndex="32" Width="100"></COLUMN>
    <COLUMN Name="DocumentFullPathAndName" Caption="DocumentFullPathAndName" Index="33" BandIndex="0" RowIndex="0" ColIndex="33" Width="100"></COLUMN>
    <COLUMN Name="DocumentName" Caption="DocumentName" Index="34" BandIndex="0" RowIndex="0" ColIndex="34" Width="100"></COLUMN>
    <COLUMN Name="DocumentNumber" Caption="DocumentNumber" Index="35" BandIndex="0" RowIndex="0" ColIndex="35" Width="100"></COLUMN>
    <COLUMN Name="DrawnBy" Caption="DrawnBy" Index="36" BandIndex="0" RowIndex="0" ColIndex="36" Width="100"></COLUMN>
    <COLUMN Name="Engineer" Caption="Engineer" Index="37" BandIndex="0" RowIndex="0" ColIndex="37" Width="100"></COLUMN>
    <COLUMN Name="Footprint" Caption="Footprint" Index="38" BandIndex="0" RowIndex="0" ColIndex="38" Width="100"></COLUMN>
    <COLUMN Name="Height_Mil_" Caption="Height&#40;Mil&#41;" Index="39" BandIndex="0" RowIndex="0" ColIndex="39" Width="100"></COLUMN>
    <COLUMN Name="Height_mm_" Caption="Height&#40;mm&#41;" Index="40" BandIndex="0" RowIndex="0" ColIndex="40" Width="100"></COLUMN>
    <COLUMN Name="Ibis_Model" Caption="Ibis Model" Index="41" BandIndex="0" RowIndex="0" ColIndex="41" Width="100"></COLUMN>
    <COLUMN Name="ImagePath" Caption="ImagePath" Index="42" BandIndex="0" RowIndex="0" ColIndex="42" Width="100"></COLUMN>
    <COLUMN Name="Index" Caption="Index" Index="43" BandIndex="0" RowIndex="0" ColIndex="43" Width="100"></COLUMN>
    <COLUMN Name="ItemGUID" Caption="ItemGUID" Index="44" BandIndex="0" RowIndex="0" ColIndex="44" Width="100"></COLUMN>
    <COLUMN Name="LatestRevisionDate" Caption="LatestRevisionDate" Index="45" BandIndex="0" RowIndex="0" ColIndex="45" Width="100"></COLUMN>
    <COLUMN Name="LatestRevisionNote" Caption="LatestRevisionNote" Index="46" BandIndex="0" RowIndex="0" ColIndex="46" Width="100"></COLUMN>
    <COLUMN Name="Library_Name" Caption="Library Name" Index="47" BandIndex="0" RowIndex="0" ColIndex="47" Width="100"></COLUMN>
    <COLUMN Name="Library_Reference" Caption="Library Reference" Index="48" BandIndex="0" RowIndex="0" ColIndex="48" Width="100"></COLUMN>
    <COLUMN Name="LibRef" Caption="LibRef" Index="49" BandIndex="0" RowIndex="0" ColIndex="49" Width="100"></COLUMN>
    <COLUMN Name="LogicalDesignator" Caption="LogicalDesignator" Index="50" BandIndex="0" RowIndex="0" ColIndex="50" Width="100"></COLUMN>
    <COLUMN Name="Manufacturer" Caption="Manufacturer" Index="51" BandIndex="0" RowIndex="0" ColIndex="51" Width="100"></COLUMN>
    <COLUMN Name="Model_Footprint" Caption="Model:Footprint" Index="52" BandIndex="0" RowIndex="0" ColIndex="52" Width="100"></COLUMN>
    <COLUMN Name="Model_PCB3D" Caption="Model:PCB3D" Index="53" BandIndex="0" RowIndex="0" ColIndex="53" Width="100"></COLUMN>
    <COLUMN Name="Model_Signal_Integrity" Caption="Model:Signal Integrity" Index="54" BandIndex="0" RowIndex="0" ColIndex="54" Width="100"></COLUMN>
    <COLUMN Name="Model_Simulation" Caption="Model:Simulation" Index="55" BandIndex="0" RowIndex="0" ColIndex="55" Width="100"></COLUMN>
    <COLUMN Name="Models" Caption="Models" Index="56" BandIndex="0" RowIndex="0" ColIndex="56" Width="100"></COLUMN>
    <COLUMN Name="ModifiedDate" Caption="ModifiedDate" Index="57" BandIndex="0" RowIndex="0" ColIndex="57" Width="100"></COLUMN>
    <COLUMN Name="MountType" Caption="MountType" Index="58" BandIndex="0" RowIndex="0" ColIndex="58" Width="100"></COLUMN>
    <COLUMN Name="Organization" Caption="Organization" Index="59" BandIndex="0" RowIndex="0" ColIndex="59" Width="100"></COLUMN>
    <COLUMN Name="PackageDescription" Caption="PackageDescription" Index="60" BandIndex="0" RowIndex="0" ColIndex="60" Width="100"></COLUMN>
    <COLUMN Name="PackageReference" Caption="PackageReference" Index="61" BandIndex="0" RowIndex="0" ColIndex="61" Width="100"></COLUMN>
    <COLUMN Name="PackageVersion" Caption="PackageVersion" Index="62" BandIndex="0" RowIndex="0" ColIndex="62" Width="100"></COLUMN>
    <COLUMN Name="PageSetup" Caption="PageSetup" Index="63" BandIndex="0" RowIndex="0" ColIndex="63" Width="100"></COLUMN>
    <COLUMN Name="PartNumber" Caption="PartNumber" Index="64" BandIndex="0" RowIndex="0" ColIndex="64" Width="100"></COLUMN>
    <COLUMN Name="PartType" Caption="PartType" Index="65" BandIndex="0" RowIndex="0" ColIndex="65" Width="100"></COLUMN>
    <COLUMN Name="PCB3D" Caption="PCB3D" Index="66" BandIndex="0" RowIndex="0" ColIndex="66" Width="100"></COLUMN>
    <COLUMN Name="PhysicalPath" Caption="PhysicalPath" Index="67" BandIndex="0" RowIndex="0" ColIndex="67" Width="100"></COLUMN>
    <COLUMN Name="Pins" Caption="Pins" Index="68" BandIndex="0" RowIndex="0" ColIndex="68" Width="100"></COLUMN>
    <COLUMN Name="Project" Caption="Project" Index="69" BandIndex="0" RowIndex="0" ColIndex="69" Width="100"></COLUMN>
    <COLUMN Name="ProjectName" Caption="ProjectName" Index="70" BandIndex="0" RowIndex="0" ColIndex="70" Width="100"></COLUMN>
    <COLUMN Name="Published" Caption="Published" Index="71" BandIndex="0" RowIndex="0" ColIndex="71" Width="100"></COLUMN>
    <COLUMN Name="Publisher" Caption="Publisher" Index="72" BandIndex="0" RowIndex="0" ColIndex="72" Width="100"></COLUMN>
    <COLUMN Name="Quantity" Caption="Quantity" Index="73" BandIndex="0" RowIndex="0" ColIndex="73" Width="100"></COLUMN>
    <COLUMN Name="Revision" Caption="Revision" Index="74" BandIndex="0" RowIndex="0" ColIndex="74" Width="100"></COLUMN>
    <COLUMN Name="RevisionGUID" Caption="RevisionGUID" Index="75" BandIndex="0" RowIndex="0" ColIndex="75" Width="100"></COLUMN>
    <COLUMN Name="RoHS" Caption="RoHS" Index="76" BandIndex="0" RowIndex="0" ColIndex="76" Width="100"></COLUMN>
    <COLUMN Name="Rule" Caption="Rule" Index="77" BandIndex="0" RowIndex="0" ColIndex="77" Width="100"></COLUMN>
    <COLUMN Name="SheetNumber" Caption="SheetNumber" Index="78" BandIndex="0" RowIndex="0" ColIndex="78" Width="100"></COLUMN>
    <COLUMN Name="SheetTotal" Caption="SheetTotal" Index="79" BandIndex="0" RowIndex="0" ColIndex="79" Width="100"></COLUMN>
    <COLUMN Name="Signal_Integrity" Caption="Signal Integrity" Index="80" BandIndex="0" RowIndex="0" ColIndex="80" Width="100"></COLUMN>
    <COLUMN Name="Simulation" Caption="Simulation" Index="81" BandIndex="0" RowIndex="0" ColIndex="81" Width="100"></COLUMN>
    <COLUMN Name="SourceLibraryName" Caption="SourceLibraryName" Index="82" BandIndex="0" RowIndex="0" ColIndex="82" Width="100"></COLUMN>
    <COLUMN Name="Sub_Parts" Caption="Sub-Parts" Index="83" BandIndex="0" RowIndex="0" ColIndex="83" Width="100"></COLUMN>
    <COLUMN Name="SymbolCreator" Caption="SymbolCreator" Index="84" BandIndex="0" RowIndex="0" ColIndex="84" Width="100"></COLUMN>
    <COLUMN Name="SymbolVersion" Caption="SymbolVersion" Index="85" BandIndex="0" RowIndex="0" ColIndex="85" Width="100"></COLUMN>
    <COLUMN Name="Time" Caption="Time" Index="86" BandIndex="0" RowIndex="0" ColIndex="86" Width="100"></COLUMN>
    <COLUMN Name="Title" Caption="Title" Index="87" BandIndex="0" RowIndex="0" ColIndex="87" Width="100"></COLUMN>
    <COLUMN Name="U_M" Caption="U/M" Index="88" BandIndex="0" RowIndex="0" ColIndex="88" Width="100"></COLUMN>
    <COLUMN Name="UniqueIdName" Caption="UniqueIdName" Index="89" BandIndex="0" RowIndex="0" ColIndex="89" Width="100"></COLUMN>
    <COLUMN Name="UniqueIdPath" Caption="UniqueIdPath" Index="90" BandIndex="0" RowIndex="0" ColIndex="90" Width="100"></COLUMN>
    <COLUMN Name="Value" Caption="Value" Index="91" BandIndex="0" RowIndex="0" ColIndex="91" Width="100"></COLUMN>
    <COLUMN Name="Variant" Caption="Variant" Index="92" BandIndex="0" RowIndex="0" ColIndex="92" Width="100"></COLUMN>
    <COLUMN Name="VaultGUID" Caption="VaultGUID" Index="93" BandIndex="0" RowIndex="0" ColIndex="93" Width="100"></COLUMN>
    <COLUMN Name="_" Caption="&#35;" Index="94" BandIndex="0" RowIndex="0" ColIndex="94" Width="100"></COLUMN>
    <COLUMN Name="_ID_" Caption="&#37;ID&#37;" Index="95" BandIndex="0" RowIndex="0" ColIndex="95" Width="100"></COLUMN>
    <COLUMN Name="_PARENTID_" Caption="&#37;PARENTID&#37;" Index="96" BandIndex="0" RowIndex="0" ColIndex="96" Width="100"></COLUMN>
  </COLUMNS>
  <ROWS>
    <ROW Address1="" Address2="" Address3="" Address4="" Alternate_Manufacturer="" Alternate_PartNumber="" Application_BuildNumber="" ApprovedBy="" Author="" CheckedBy="" Code_IPC="" Code_JEDEC="" Comment="104" CompanyName="" Component_Kind="Standard" ComponentKind="0" ComponentLink1Description="" ComponentLink1URL="" ComponentLink2Description="" ComponentLink2URL="" CompType="" CurrentDate="2/14/2016" CurrentTime="5:04:01 PM" DatasheetVersion="" Date="" Description="Capacitor" Designator="C1_MotorEncoder1" Designator_X_Mil_="1190" Designator_X_mm_="30.226" Designator_Y_Mil_="3210" Designator_Y_mm_="81.534" DesignItemId="Cap" Document="C:&#92;Users&#92;Keshuai&#92;Documents&#92;SmartMouse2016&#92;BrushlessMotorAndEncoder.SchDoc" DocumentFullPathAndName="C:&#92;Users&#92;Keshuai&#92;Documents&#92;SmartMouse2016&#92;BrushlessMotorAndEncoder.SchDoc" DocumentName="BrushlessMotorAndEncoder.SchDoc" DocumentNumber="" DrawnBy="" Engineer="" Footprint="CAP_0805" Height_Mil_="0" Height_mm_="0" Ibis_Model="" ImagePath="" Index="1" ItemGUID="" LatestRevisionDate="17-Jul-2002" LatestRevisionNote="Re-released for DXP Platform." Library_Name="Miscellaneous Devices.IntLib" Library_Reference="Cap" LibRef="Cap" LogicalDesignator="C1" Manufacturer="" Model_Footprint="" Model_PCB3D="" Model_Signal_Integrity="" Model_Simulation="Capacitor" Models="3" ModifiedDate="1/6/2016" MountType="" Organization="" PackageDescription="Radial Cap, Thru-Hole; 2 Leads; 0.3 in Pin Spacing" PackageReference="RAD-0.3" PackageVersion="" PageSetup="" PartNumber="" PartType="104" PCB3D="" PhysicalPath="Sheet1&#92;MotorEncoder1" Pins="2" Project="C:&#92;Users&#92;Keshuai&#92;Documents&#92;SmartMouse2016&#92;SmartMouse2016.PrjPcb" ProjectName="SmartMouse2016.PrjPcb" Published="8-Jun-2000" Publisher="Altium Limited" Quantity="1" Revision="" RevisionGUID="" RoHS="" Rule="" SheetNumber=".1" SheetTotal="20" Signal_Integrity="Cap" Simulation="CAP" SourceLibraryName="Miscellaneous Devices.IntLib" Sub_Parts="1" SymbolCreator="" SymbolVersion="" Time="" Title="" U_M="" UniqueIdName="KOKHWWSO" UniqueIdPath="&#92;1RFADJOKD" Value="100pF" Variant="" VaultGUID="" _="1" _ID_="1323122032" _PARENTID_=""></ROW>
    <ROW Address1="" Address2="" Address3="" Address4="" Alternate_Manufacturer="" Alternate_PartNumber="" Application_BuildNumber="" ApprovedBy="" Author="" CheckedBy="" Code_IPC="" Code_JEDEC="" Comment="104" CompanyName="" Component_Kind="Standard" ComponentKind="0" ComponentLink1Description="" ComponentLink1URL="" ComponentLink2Description="" ComponentLink2URL="" CompType="" CurrentDate="2/14/2016" CurrentTime="5:04:01 PM" DatasheetVersion="" Date="" Description="Capacitor" Designator="C1_MotorEncoder2" Designator_X_Mil_="1190" Designator_X_mm_="30.226" Designator_Y_Mil_="3210" Designator_Y_mm_="81.534" DesignItemId="Cap" Document="C:&#92;Users&#92;Keshuai&#92;Documents&#92;SmartMouse2016&#92;BrushlessMotorAndEncoder.SchDoc" DocumentFullPathAndName="C:&#92;Users&#92;Keshuai&#92;Documents&#92;SmartMouse2016&#92;BrushlessMotorAndEncoder.SchDoc" DocumentName="BrushlessMotorAndEncoder.SchDoc" DocumentNumber="" DrawnBy="" Engineer="" Footprint="CAP_0805" Height_Mil_="0" Height_mm_="0" Ibis_Model="" ImagePath="" Index="2" ItemGUID="" LatestRevisionDate="17-Jul-2002" LatestRevisionNote="Re-released for DXP Platform." Library_Name="Miscellaneous Devices.IntLib" Library_Reference="Cap" LibRef="Cap" LogicalDesignator="C1" Manufacturer="" Model_Footprint="" Model_PCB3D="" Model_Signal_Integrity="" Model_Simulation="Capacitor" Models="3" ModifiedDate="1/6/2016" MountType="" Organization="" PackageDescription="Radial Cap, Thru-Hole; 2 Leads; 0.3 in Pin Spacing" PackageReference="RAD-0.3" PackageVersion="" PageSetup="" PartNumber="" PartType="104" PCB3D="" PhysicalPath="Sheet1&#92;MotorEncoder2" Pins="2" Project="C:&#92;Users&#92;Keshuai&#92;Documents&#92;SmartMouse2016&#92;SmartMouse2016.PrjPcb" ProjectName="SmartMouse2016.PrjPcb" Published="8-Jun-2000" Publisher="Altium Limited" Quantity="1" Revision="" RevisionGUID="" RoHS="" Rule="" SheetNumber=".2" SheetTotal="20" Signal_Integrity="Cap" Simulation="CAP" SourceLibraryName="Miscellaneous Devices.IntLib" Sub_Parts="1" SymbolCreator="" SymbolVersion="" Time="" Title="" U_M="" UniqueIdName="KOKHWWSO" UniqueIdPath="&#92;2RFADJOKD" Value="100pF" Variant="" VaultGUID="" _="2" _ID_="1323122128" _PARENTID_=""></ROW>
    <ROW Address1="" Address2="" Address3="" Address4="" Alternate_Manufacturer="" Alternate_PartNumber="" Application_BuildNumber="" ApprovedBy="" Author="" CheckedBy="" Code_IPC="" Code_JEDEC="" Comment="alu cap from trash &#62;20v" CompanyName="" Component_Kind="Standard" ComponentKind="0" ComponentLink1Description="" ComponentLink1URL="" ComponentLink2Description="" ComponentLink2URL="" CompType="" CurrentDate="2/20/2016" CurrentTime="3:39:48 PM" DatasheetVersion="" Date="" Description="" Designator="C2" Designator_X_Mil_="6100" Designator_X_mm_="154.94" Designator_Y_Mil_="6400" Designator_Y_mm_="162.56" DesignItemId="CAP_POLD" Document="C:&#92;Users&#92;Keshuai&#92;Documents&#92;SmartMouse2016&#92;Power.SchDoc" DocumentFullPathAndName="C:&#92;Users&#92;Keshuai&#92;Documents&#92;SmartMouse2016&#92;Power.SchDoc" DocumentName="Power.SchDoc" DocumentNumber="" DrawnBy="" Engineer="" Footprint="PANASONIC_D" Height_Mil_="0" Height_mm_="0" Ibis_Model="" ImagePath="" Index="3" ItemGUID="" LatestRevisionDate="" LatestRevisionNote="" Library_Name="SparkFun-Passives.IntLib" Library_Reference="CAP_POLD" LibRef="CAP_POLD" LogicalDesignator="C2" Manufacturer="" Model_Footprint="" Model_PCB3D="" Model_Signal_Integrity="" Model_Simulation="" Models="1" ModifiedDate="2/20/2016" MountType="" Organization="" PackageDescription="" PackageReference="" PackageVersion="" PageSetup="" PartNumber="" PartType="alu cap from trash &#62;20v" PCB3D="" PhysicalPath="Sheet1&#92;U_Power" Pins="2" Project="C:&#92;Users&#92;Keshuai&#92;Documents&#92;SmartMouse2016&#92;SmartMouse2016.PrjPcb" ProjectName="SmartMouse2016.PrjPcb" Published="" Publisher="" Quantity="1" Revision="" RevisionGUID="" RoHS="" Rule="" SheetNumber="" SheetTotal="20" Signal_Integrity="" Simulation="" SourceLibraryName="SparkFun-Passives.IntLib" Sub_Parts="1" SymbolCreator="" SymbolVersion="" Time="" Title="" U_M="" UniqueIdName="DFLVUUTS" UniqueIdPath="&#92;LQNDIOHO" Value="" Variant="" VaultGUID="" _="3" _ID_="1323122224" _PARENTID_=""></ROW>
    <ROW Address1="" Address2="" Address3="" Address4="" Alternate_Manufacturer="" Alternate_PartNumber="" Application_BuildNumber="" ApprovedBy="" Author="" CheckedBy="" Code_IPC="" Code_JEDEC="" Comment="104" CompanyName="" Component_Kind="Standard" ComponentKind="0" ComponentLink1Description="" ComponentLink1URL="" ComponentLink2Description="" ComponentLink2URL="" CompType="" CurrentDate="2/14/2016" CurrentTime="5:04:01 PM" DatasheetVersion="" Date="" Description="Capacitor" Designator="C4_MotorEncoder1" Designator_X_Mil_="2390" Designator_X_mm_="60.706" Designator_Y_Mil_="3210" Designator_Y_mm_="81.534" DesignItemId="Cap" Document="C:&#92;Users&#92;Keshuai&#92;Documents&#92;SmartMouse2016&#92;BrushlessMotorAndEncoder.SchDoc" DocumentFullPathAndName="C:&#92;Users&#92;Keshuai&#92;Documents&#92;SmartMouse2016&#92;BrushlessMotorAndEncoder.SchDoc" DocumentName="BrushlessMotorAndEncoder.SchDoc" DocumentNumber="" DrawnBy="" Engineer="" Footprint="CAP_0805" Height_Mil_="0" Height_mm_="0" Ibis_Model="" ImagePath="" Index="4" ItemGUID="" LatestRevisionDate="17-Jul-2002" LatestRevisionNote="Re-released for DXP Platform." Library_Name="Miscellaneous Devices.IntLib" Library_Reference="Cap" LibRef="Cap" LogicalDesignator="C4" Manufacturer="" Model_Footprint="" Model_PCB3D="" Model_Signal_Integrity="" Model_Simulation="Capacitor" Models="3" ModifiedDate="1/6/2016" MountType="" Organization="" PackageDescription="Radial Cap, Thru-Hole; 2 Leads; 0.3 in Pin Spacing" PackageReference="RAD-0.3" PackageVersion="" PageSetup="" PartNumber="" PartType="104" PCB3D="" PhysicalPath="Sheet1&#92;MotorEncoder1" Pins="2" Project="C:&#92;Users&#92;Keshuai&#92;Documents&#92;SmartMouse2016&#92;SmartMouse2016.PrjPcb" ProjectName="SmartMouse2016.PrjPcb" Published="8-Jun-2000" Publisher="Altium Limited" Quantity="1" Revision="" RevisionGUID="" RoHS="" Rule="" SheetNumber=".1" SheetTotal="20" Signal_Integrity="Cap" Simulation="CAP" SourceLibraryName="Miscellaneous Devices.IntLib" Sub_Parts="1" SymbolCreator="" SymbolVersion="" Time="" Title="" U_M="" UniqueIdName="AFQOJJVE" UniqueIdPath="&#92;1RFADJOKD" Value="100pF" Variant="" VaultGUID="" _="4" _ID_="1323122320" _PARENTID_=""></ROW>
    <ROW Address1="" Address2="" Address3="" Address4="" Alternate_Manufacturer="" Alternate_PartNumber="" Application_BuildNumber="" ApprovedBy="" Author="" CheckedBy="" Code_IPC="" Code_JEDEC="" Comment="104" CompanyName="" Component_Kind="Standard" ComponentKind="0" ComponentLink1Description="" ComponentLink1URL="" ComponentLink2Description="" ComponentLink2URL="" CompType="" CurrentDate="2/14/2016" CurrentTime="5:04:01 PM" DatasheetVersion="" Date="" Description="Capacitor" Designator="C4_MotorEncoder2" Designator_X_Mil_="2390" Designator_X_mm_="60.706" Designator_Y_Mil_="3210" Designator_Y_mm_="81.534" DesignItemId="Cap" Document="C:&#92;Users&#92;Keshuai&#92;Documents&#92;SmartMouse2016&#92;BrushlessMotorAndEncoder.SchDoc" DocumentFullPathAndName="C:&#92;Users&#92;Keshuai&#92;Documents&#92;SmartMouse2016&#92;BrushlessMotorAndEncoder.SchDoc" DocumentName="BrushlessMotorAndEncoder.SchDoc" DocumentNumber="" DrawnBy="" Engineer="" Footprint="CAP_0805" Height_Mil_="0" Height_mm_="0" Ibis_Model="" ImagePath="" Index="5" ItemGUID="" LatestRevisionDate="17-Jul-2002" LatestRevisionNote="Re-released for DXP Platform." Library_Name="Miscellaneous Devices.IntLib" Library_Reference="Cap" LibRef="Cap" LogicalDesignator="C4" Manufacturer="" Model_Footprint="" Model_PCB3D="" Model_Signal_Integrity="" Model_Simulation="Capacitor" Models="3" ModifiedDate="1/6/2016" MountType="" Organization="" PackageDescription="Radial Cap, Thru-Hole; 2 Leads; 0.3 in Pin Spacing" PackageReference="RAD-0.3" PackageVersion="" PageSetup="" PartNumber="" PartType="104" PCB3D="" PhysicalPath="Sheet1&#92;MotorEncoder2" Pins="2" Project="C:&#92;Users&#92;Keshuai&#92;Documents&#92;SmartMouse2016&#92;SmartMouse2016.PrjPcb" ProjectName="SmartMouse2016.PrjPcb" Published="8-Jun-2000" Publisher="Altium Limited" Quantity="1" Revision="" RevisionGUID="" RoHS="" Rule="" SheetNumber=".2" SheetTotal="20" Signal_Integrity="Cap" Simulation="CAP" SourceLibraryName="Miscellaneous Devices.IntLib" Sub_Parts="1" SymbolCreator="" SymbolVersion="" Time="" Title="" U_M="" UniqueIdName="AFQOJJVE" UniqueIdPath="&#92;2RFADJOKD" Value="100pF" Variant="" VaultGUID="" _="5" _ID_="1323122416" _PARENTID_=""></ROW>